version: "1.0"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: pinterest-clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports: 
      - "5432:5432"
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  backend:
    container_name: backend
    ports:
      - "3000:3000"
    build:
      context: ./pinterest-clone-backend
      dockerfile: Dockerfile
    depends_on:
    - postgres
    environment:
    - DB_HOST=postgres
    - DB_PORT=5432


  frontend:
    build:
      context: ./pinterest-fe
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_REST_ENDPOINT=backend/api
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
volumes:
  docker-nest-postgres: